# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20160622_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ('scheduled_time',)},
        ),
    ]
