# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20160622_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_id', to='schedule.Users'),
        ),
    ]
