# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20160623_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='deleted_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set([('user', 'task', 'scheduled_time')]),
        ),
    ]
