# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 06:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20160627_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 27, 6, 36, 7, 487797, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 27, 6, 36, 16, 983232, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=1000),
        ),
    ]
